mv DS001.cpp "비만 판정하기.cpp"
mv DS002.cpp "좌표 2개를 입력받은 후 좌표간 거리 계산.cpp"
mv DS003.cpp "날짜(월,일)를 입력받아 1년 중 몇번째 날인지 계산.cpp"
mv DS004.cpp "국,영,수 과목 점수를 입력받아 총점과 평균을 계산하고, 등급 판정.cpp"
mv DS005.cpp "알파벳 개수 세기.cpp"
mv DS006.cpp "전공 3과목의 GPA 계산하기.cpp"
mv DS007.cpp "문장을 숫자로 변환하기 (버전1).cpp"
mv DS008.cpp "문장을 숫자로 변환하기 (버전2).cpp"
mv DS009.cpp "생활관 호실 배정 프로그램.cpp"
mv DS011.cpp "입력한 수의 전체 합과 최대값 구하기.cpp"
mv DS012.cpp "구조체 비교하기.cpp"
mv DS013.cpp "카페 메뉴 관리하기.cpp"
mv DS014.cpp "문장의 앞뒤 공백 제거하기.cpp"
mv DS015.cpp "마지막 단어의 길이 구하기.cpp"
mv DS016.cpp "prefix 문자열 구하기.cpp"
mv DS021.cpp "성적 계산하기.cpp"
mv DS022.cpp "졸업영어성적 판단하기.cpp"
mv DS023.cpp "쇼핑몰 상품 정보 관리.cpp"
mv DS024.cpp "수강신청 프로그램 (C++ 버전).cpp"
mv DS031.cpp "MyStack 만들기.cpp"
mv DS032.cpp "GPA 분석하기.cpp"
mv DS033.cpp "쿠폰 관리기.cpp"
mv DS041.cpp "MyLinkedStack 만들기.cpp"
mv DS042.cpp "MyLinkedStack을 이용한 계산기.cpp"
mv DS043.cpp "사용자가 입력한 문자열 알아내기.cpp"
